services:
  database:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"

  web:
    depends_on:
      - database
    build:
      context: .
      dockerfile: web.Dockerfile
    command: sh -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 config.wsgi"
    environment:
      DEBUG: "${DJANGO_DEBUG}"
      SECRET_KEY: "${DJANGO_SECRET_KEY}"
      ALLOWED_HOSTS: "${DJANGO_ALLOWED_HOSTS}"
      CSRF_TRUSTED_ORIGINS: "${DJANGO_CSRF_TRUSTED_ORIGINS}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"

  web-server:
    depends_on:
      - web
    build:
      context: .
      dockerfile: web-server.Dockerfile
    ports:
      - "8080:80"

volumes:
  database:
