# Generated by Django 4.2 on 2023-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="estado"
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(max_length=2, unique=True, verbose_name="sigla"),
                ),
            ],
        ),
    ]
