# Generated by Django 4.2 on 2023-04-15 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteka", "0002_populate_states"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borrower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="nome")),
                ("birthdate", models.DateField(verbose_name="data de nascimento")),
                (
                    "cpf",
                    models.CharField(max_length=11, unique=True, verbose_name="CPF"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="celular")),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default=None,
                        max_length=254,
                        null=True,
                        verbose_name="email",
                    ),
                ),
                ("zip_code", models.CharField(max_length=8, verbose_name="cep")),
                ("address", models.CharField(max_length=255, verbose_name="endereço")),
                ("city", models.CharField(max_length=100, verbose_name="cidade")),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="biblioteka.countrystate",
                        verbose_name="estado",
                    ),
                ),
            ],
        ),
    ]
