# Generated by Django 4.2 on 2023-05-07 02:41

import biblioteka.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteka", "0005_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="address",
            field=models.CharField(
                max_length=255,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace,
                ],
                verbose_name="endereço",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="birthdate",
            field=models.DateField(
                validators=[
                    biblioteka.models.validate_date_not_in_future,
                    biblioteka.models.validate_date_at_least_1900,
                ],
                verbose_name="data de nascimento",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="city",
            field=models.CharField(
                max_length=100,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace,
                ],
                verbose_name="cidade",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="cpf",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_whitespace,
                    biblioteka.models.validate_only_digits,
                    django.core.validators.MinLengthValidator(
                        11, "CPF deve conter 11 dígitos"
                    ),
                ],
                verbose_name="CPF",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace,
                ],
                verbose_name="nome",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_whitespace,
                    biblioteka.models.validate_only_digits,
                    django.core.validators.MinLengthValidator(
                        10, "Telefone deve conter no mínimo 10 dígitos (incluindo DDD)"
                    ),
                ],
                verbose_name="celular",
            ),
        ),
        migrations.AlterField(
            model_name="borrower",
            name="zip_code",
            field=models.CharField(
                max_length=8,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_whitespace,
                    biblioteka.models.validate_only_digits,
                    django.core.validators.MinLengthValidator(
                        8, "CEP deve conter 8 dígitos"
                    ),
                ],
                verbose_name="cep",
            ),
        ),
    ]
