# Generated by Django 4.2 on 2023-05-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteka", "0006_add_borrower_validation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="inventory_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="ID do estoque"
            ),
        ),
    ]
