# Generated by Django 4.2 on 2023-05-07 22:07

import biblioteka.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteka", "0007_alter_book_inventory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                validators=[
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace
                ],
                verbose_name="autor",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=1000,
                null=True,
                validators=[
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace
                ],
                verbose_name="descrição",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                validators=[
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace
                ],
                verbose_name="gênero",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="inventory_id",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[biblioteka.models.validate_not_empty],
                verbose_name="ID do estoque",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                max_length=13,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_whitespace,
                    biblioteka.models.validate_only_digits,
                    biblioteka.models.Book.validate_10_or_13_characters,
                    django.core.validators.MinLengthValidator(
                        10, "ISBN deve conter no mínimo 10 dígitos"
                    ),
                ],
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=100,
                null=True,
                validators=[
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace
                ],
                verbose_name="idioma",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                validators=[
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace
                ],
                verbose_name="editora",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                validators=[
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace
                ],
                verbose_name="subtítulo",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    biblioteka.models.validate_not_empty,
                    biblioteka.models.validate_no_leading_trailing_consecutive_whitespace,
                ],
                verbose_name="título",
            ),
        ),
    ]
