# Generated by Django 4.2 on 2023-05-16 22:39

import django.db.models.deletion
from django.db import migrations, models

import biblioteka.models


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteka", "0008_alter_book_author_alter_book_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_period",
                    models.IntegerField(verbose_name="prazo de empréstimo"),
                ),
            ],
            options={
                "verbose_name": "opções de empréstimo",
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrowed_date",
                    models.DateField(
                        validators=[biblioteka.models.validate_date_not_in_future],
                        verbose_name="data de locação",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="prazo de devolução")),
                (
                    "returned_date",
                    models.DateField(
                        null=True,
                        validators=[biblioteka.models.validate_date_not_in_future],
                        verbose_name="data de devolução",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="biblioteka.book",
                        verbose_name="livro",
                    ),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="biblioteka.borrower",
                        verbose_name="cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "empréstimo",
            },
        ),
        migrations.AddConstraint(
            model_name="loan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("returned_date", None)),
                fields=("book",),
                name="one_active_loan_per_book",
            ),
        ),
    ]
