# Generated by Django 4.2 on 2023-05-16 22:47

from django.db import migrations


def set_loan_period(apps, schema_editor):
    LoanOptions = apps.get_model("biblioteka", "LoanOptions")

    loan_options = LoanOptions(loan_period=7)

    loan_options.save()


class Migration(migrations.Migration):
    dependencies = [
        ("biblioteka", "0009_loanoptions_loan_loan_one_active_loan_per_book"),
    ]

    operations = [migrations.RunPython(set_loan_period)]
